//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GettingStartedClient.IISSSLServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IISSSLServiceRef.ISSLServiceIIS")]
    public interface ISSLServiceIIS {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://Microsoft.ServiceModel.Samples) of message AddRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Add", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/AddResponse")]
        GettingStartedClient.IISSSLServiceRef.AddResponse Add(GettingStartedClient.IISSSLServiceRef.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Add", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/AddResponse")]
        System.Threading.Tasks.Task<GettingStartedClient.IISSSLServiceRef.AddResponse> AddAsync(GettingStartedClient.IISSSLServiceRef.AddRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://Microsoft.ServiceModel.Samples) of message SubtractRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Subtract", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/SubtractResponse")]
        GettingStartedClient.IISSSLServiceRef.SubtractResponse Subtract(GettingStartedClient.IISSSLServiceRef.SubtractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Subtract", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/SubtractResponse")]
        System.Threading.Tasks.Task<GettingStartedClient.IISSSLServiceRef.SubtractResponse> SubtractAsync(GettingStartedClient.IISSSLServiceRef.SubtractRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://Microsoft.ServiceModel.Samples) of message MultiplyRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Multiply", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/MultiplyResponse")]
        GettingStartedClient.IISSSLServiceRef.MultiplyResponse Multiply(GettingStartedClient.IISSSLServiceRef.MultiplyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Multiply", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/MultiplyResponse")]
        System.Threading.Tasks.Task<GettingStartedClient.IISSSLServiceRef.MultiplyResponse> MultiplyAsync(GettingStartedClient.IISSSLServiceRef.MultiplyRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://Microsoft.ServiceModel.Samples) of message DivideRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Divide", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/DivideResponse")]
        GettingStartedClient.IISSSLServiceRef.DivideResponse Divide(GettingStartedClient.IISSSLServiceRef.DivideRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Divide", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/DivideResponse")]
        System.Threading.Tasks.Task<GettingStartedClient.IISSSLServiceRef.DivideResponse> DivideAsync(GettingStartedClient.IISSSLServiceRef.DivideRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public double n1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=1)]
        public double n2;
        
        public AddRequest() {
        }
        
        public AddRequest(double n1, double n2) {
            this.n1 = n1;
            this.n2 = n2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public double AddResult;
        
        public AddResponse() {
        }
        
        public AddResponse(double AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Subtract", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class SubtractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public double n1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=1)]
        public double n2;
        
        public SubtractRequest() {
        }
        
        public SubtractRequest(double n1, double n2) {
            this.n1 = n1;
            this.n2 = n2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubtractResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class SubtractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public double SubtractResult;
        
        public SubtractResponse() {
        }
        
        public SubtractResponse(double SubtractResult) {
            this.SubtractResult = SubtractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Multiply", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class MultiplyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public double n1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=1)]
        public double n2;
        
        public MultiplyRequest() {
        }
        
        public MultiplyRequest(double n1, double n2) {
            this.n1 = n1;
            this.n2 = n2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MultiplyResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class MultiplyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public double MultiplyResult;
        
        public MultiplyResponse() {
        }
        
        public MultiplyResponse(double MultiplyResult) {
            this.MultiplyResult = MultiplyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Divide", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class DivideRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public double n1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=1)]
        public double n2;
        
        public DivideRequest() {
        }
        
        public DivideRequest(double n1, double n2) {
            this.n1 = n1;
            this.n2 = n2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DivideResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class DivideResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public double DivideResult;
        
        public DivideResponse() {
        }
        
        public DivideResponse(double DivideResult) {
            this.DivideResult = DivideResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISSLServiceIISChannel : GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SSLServiceIISClient : System.ServiceModel.ClientBase<GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS>, GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS {
        
        public SSLServiceIISClient() {
        }
        
        public SSLServiceIISClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SSLServiceIISClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSLServiceIISClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSLServiceIISClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GettingStartedClient.IISSSLServiceRef.AddResponse GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS.Add(GettingStartedClient.IISSSLServiceRef.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public double Add(double n1, double n2) {
            GettingStartedClient.IISSSLServiceRef.AddRequest inValue = new GettingStartedClient.IISSSLServiceRef.AddRequest();
            inValue.n1 = n1;
            inValue.n2 = n2;
            GettingStartedClient.IISSSLServiceRef.AddResponse retVal = ((GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS)(this)).Add(inValue);
            return retVal.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GettingStartedClient.IISSSLServiceRef.AddResponse> GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS.AddAsync(GettingStartedClient.IISSSLServiceRef.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<GettingStartedClient.IISSSLServiceRef.AddResponse> AddAsync(double n1, double n2) {
            GettingStartedClient.IISSSLServiceRef.AddRequest inValue = new GettingStartedClient.IISSSLServiceRef.AddRequest();
            inValue.n1 = n1;
            inValue.n2 = n2;
            return ((GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GettingStartedClient.IISSSLServiceRef.SubtractResponse GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS.Subtract(GettingStartedClient.IISSSLServiceRef.SubtractRequest request) {
            return base.Channel.Subtract(request);
        }
        
        public double Subtract(double n1, double n2) {
            GettingStartedClient.IISSSLServiceRef.SubtractRequest inValue = new GettingStartedClient.IISSSLServiceRef.SubtractRequest();
            inValue.n1 = n1;
            inValue.n2 = n2;
            GettingStartedClient.IISSSLServiceRef.SubtractResponse retVal = ((GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS)(this)).Subtract(inValue);
            return retVal.SubtractResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GettingStartedClient.IISSSLServiceRef.SubtractResponse> GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS.SubtractAsync(GettingStartedClient.IISSSLServiceRef.SubtractRequest request) {
            return base.Channel.SubtractAsync(request);
        }
        
        public System.Threading.Tasks.Task<GettingStartedClient.IISSSLServiceRef.SubtractResponse> SubtractAsync(double n1, double n2) {
            GettingStartedClient.IISSSLServiceRef.SubtractRequest inValue = new GettingStartedClient.IISSSLServiceRef.SubtractRequest();
            inValue.n1 = n1;
            inValue.n2 = n2;
            return ((GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS)(this)).SubtractAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GettingStartedClient.IISSSLServiceRef.MultiplyResponse GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS.Multiply(GettingStartedClient.IISSSLServiceRef.MultiplyRequest request) {
            return base.Channel.Multiply(request);
        }
        
        public double Multiply(double n1, double n2) {
            GettingStartedClient.IISSSLServiceRef.MultiplyRequest inValue = new GettingStartedClient.IISSSLServiceRef.MultiplyRequest();
            inValue.n1 = n1;
            inValue.n2 = n2;
            GettingStartedClient.IISSSLServiceRef.MultiplyResponse retVal = ((GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS)(this)).Multiply(inValue);
            return retVal.MultiplyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GettingStartedClient.IISSSLServiceRef.MultiplyResponse> GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS.MultiplyAsync(GettingStartedClient.IISSSLServiceRef.MultiplyRequest request) {
            return base.Channel.MultiplyAsync(request);
        }
        
        public System.Threading.Tasks.Task<GettingStartedClient.IISSSLServiceRef.MultiplyResponse> MultiplyAsync(double n1, double n2) {
            GettingStartedClient.IISSSLServiceRef.MultiplyRequest inValue = new GettingStartedClient.IISSSLServiceRef.MultiplyRequest();
            inValue.n1 = n1;
            inValue.n2 = n2;
            return ((GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS)(this)).MultiplyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GettingStartedClient.IISSSLServiceRef.DivideResponse GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS.Divide(GettingStartedClient.IISSSLServiceRef.DivideRequest request) {
            return base.Channel.Divide(request);
        }
        
        public double Divide(double n1, double n2) {
            GettingStartedClient.IISSSLServiceRef.DivideRequest inValue = new GettingStartedClient.IISSSLServiceRef.DivideRequest();
            inValue.n1 = n1;
            inValue.n2 = n2;
            GettingStartedClient.IISSSLServiceRef.DivideResponse retVal = ((GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS)(this)).Divide(inValue);
            return retVal.DivideResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GettingStartedClient.IISSSLServiceRef.DivideResponse> GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS.DivideAsync(GettingStartedClient.IISSSLServiceRef.DivideRequest request) {
            return base.Channel.DivideAsync(request);
        }
        
        public System.Threading.Tasks.Task<GettingStartedClient.IISSSLServiceRef.DivideResponse> DivideAsync(double n1, double n2) {
            GettingStartedClient.IISSSLServiceRef.DivideRequest inValue = new GettingStartedClient.IISSSLServiceRef.DivideRequest();
            inValue.n1 = n1;
            inValue.n2 = n2;
            return ((GettingStartedClient.IISSSLServiceRef.ISSLServiceIIS)(this)).DivideAsync(inValue);
        }
    }
}
